"""empty message

Revision ID: 0806c31e7a4d
Revises: b3aeab12819a
Create Date: 2022-05-27 22:37:23.762195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0806c31e7a4d'
down_revision = 'b3aeab12819a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.String(), nullable=True))
    
    op.execute("UPDATE venues SET genres = 'Alternate' WHERE genres IS NULL")
    
    op.alter_column('venues', 'genres', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
