"""empty message

Revision ID: 621400b763f5
Revises: 0806c31e7a4d
Create Date: 2022-05-27 23:01:54.517259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621400b763f5'
down_revision = '0806c31e7a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
