"""empty message

Revision ID: b3aeab12819a
Revises: e7449b700289
Create Date: 2022-05-27 08:18:36.836571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3aeab12819a'
down_revision = 'e7449b700289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
