"""empty message

Revision ID: d48e1b05ea71
Revises: 621400b763f5
Create Date: 2022-05-27 23:04:26.529965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48e1b05ea71'
down_revision = '621400b763f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.String(), nullable=True))
    
    op.execute("UPDATE venues SET genres = 'Alternate' WHERE genres IS NULL")
    
    op.alter_column('venues', 'genres', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', '_genres')
    # ### end Alembic commands ###
